// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: proto/v1/product.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductRequest) Reset() {
	*x = ProductRequest{}
	mi := &file_proto_v1_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductRequest) ProtoMessage() {}

func (x *ProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductRequest.ProtoReflect.Descriptor instead.
func (*ProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_product_proto_rawDescGZIP(), []int{0}
}

func (x *ProductRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type ProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName   string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductResponse) Reset() {
	*x = ProductResponse{}
	mi := &file_proto_v1_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductResponse) ProtoMessage() {}

func (x *ProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductResponse.ProtoReflect.Descriptor instead.
func (*ProductResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_product_proto_rawDescGZIP(), []int{1}
}

func (x *ProductResponse) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ProductResponse) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

var File_proto_v1_product_proto protoreflect.FileDescriptor

const file_proto_v1_product_proto_rawDesc = "" +
	"\n" +
	"\x16proto/v1/product.proto\x12\aproduct\"/\n" +
	"\x0eProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\"S\n" +
	"\x0fProductResponse\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName2U\n" +
	"\x0eProductService\x12C\n" +
	"\x0eGetProductById\x12\x17.product.ProductRequest\x1a\x18.product.ProductResponseB8Z6github.com/Joshdike/ecom-microservices/common/proto/v1b\x06proto3"

var (
	file_proto_v1_product_proto_rawDescOnce sync.Once
	file_proto_v1_product_proto_rawDescData []byte
)

func file_proto_v1_product_proto_rawDescGZIP() []byte {
	file_proto_v1_product_proto_rawDescOnce.Do(func() {
		file_proto_v1_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_product_proto_rawDesc), len(file_proto_v1_product_proto_rawDesc)))
	})
	return file_proto_v1_product_proto_rawDescData
}

var file_proto_v1_product_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_v1_product_proto_goTypes = []any{
	(*ProductRequest)(nil),  // 0: product.ProductRequest
	(*ProductResponse)(nil), // 1: product.ProductResponse
}
var file_proto_v1_product_proto_depIdxs = []int32{
	0, // 0: product.ProductService.GetProductById:input_type -> product.ProductRequest
	1, // 1: product.ProductService.GetProductById:output_type -> product.ProductResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_v1_product_proto_init() }
func file_proto_v1_product_proto_init() {
	if File_proto_v1_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_product_proto_rawDesc), len(file_proto_v1_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_product_proto_goTypes,
		DependencyIndexes: file_proto_v1_product_proto_depIdxs,
		MessageInfos:      file_proto_v1_product_proto_msgTypes,
	}.Build()
	File_proto_v1_product_proto = out.File
	file_proto_v1_product_proto_goTypes = nil
	file_proto_v1_product_proto_depIdxs = nil
}
